name: bots

services:
  bard-knows:
    image: bard-knows:latest
    environment:
      - TZ
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bard-knows
    networks:
      - network # Логическое имя сети внутри этого файла
    restart: unless-stopped
    volumes:
      - .:/app

networks:
  network: # Логическое имя сети внутри этого файла
    driver: bridge