version: '3.8'
services:
  bard-knows:
    image: bard-knows:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bard-knows
    restart: unless-stopped
    volumes:
      - .:/app
    command: ["python", "./app.py"]