version: '3.9'
services:
  bard-knows:
    image: bard-knows:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: bard-knows
    restart: unless-stopped
    volumes:
      - .:/app